# ------------------------
# Postgres Service Object
# ------------------------
apiVersion: v1
kind: Service
metadata:
  name: postgres-e-cloud-service
spec:
  selector:
    # ðŸ‘ˆ Must be "Pod" names, NOT "Deployment" Name
    # ðŸ‘ˆ Must CUSTOM KEY-VALUE Pairs of "Pod"
    ramos-db-app: postgres-e-cloud-pod
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
